### ISSUE TITLE
Excerpt is incorrect on archive pages

### ISSUE THREAD

**Issue by NielsdeBlaauw** [level-level/Clarkson-Core#89] opened 2017-09-29 14:15 UTC
Using `Clarkson_Object::get_excerpt()` returns an incorrect result when called in archives.

Because `the_excerpt()` uses `global $post` (which is not correctly set in an archive page) we do not get the correct excerpt for the object we are currently asking the excerpt for.

This is fixed by adding something like the following to `Clarkson_Object::get_excerpt()`

```php
	public function get_excerpt() {
		global $post;
		if(!empty($post)){
			$oldpost = clone $post;
		}else{
			$oldpost = null;
		}
		$post = $this->_post; // Set post to what we are asking the excerpt for
		if ( ! isset( $this->_excerpt ) ) {
			setup_postdata( $this->_post );
			ob_start();
			the_excerpt();
			$this->_excerpt = ob_get_clean();
			wp_reset_postdata();
		}
		$post = $oldpost; // Reset global post
		return $this->_excerpt;
	}
```

**Comment by jmslbam** [comment] 2017-09-29 18:01
Could this be a duplicate of https://github.com/level-level/Clarkson-Core/pull/58 ? @MarcZijderveld had this same behaviour. My research with a clean install could not reproduce this. And Marc couldn't either with a clean install, so we thought it would be project specific. I can't remember how he solve it within that specific project, Marc?

**Comment by NielsdeBlaauw** [comment] 2017-10-02 06:56
Steps to reproduce (done so in 3 different projects)

1. Create custom post type with `has_archive:true`.
2. Create `archive-post_type_slug.twig` in the templates directory
3. Use following template: 
```
{% for object in objects %}
    {{object.get_title()}}
    {{object.get_excerpt()}}
{% endfor %}
```

**Comment by MarcZijderveld** [comment] 2017-10-26 11:07
Probleem kwam voor in Wetlands, toen gefixt door handmatig de excerpt op te halen en te zetten.

```
 public function get_the_excerpt_custom() {
        if ( !has_excerpt($this->_post) ) {
            global $post;
            $save_post = $post;
            $post = get_post($this::get_id());
            setup_postdata( $post );
            $output = get_the_excerpt();
            $post = $save_post;
            return $output;
        }
        return $this->_post->post_excerpt;
    }
```

**Closed** 2018-01-10 16:32 UTC
Labels: bug
