### ISSUE TITLE
[ChildTheme] Twig breaks when parent theme has no templates folder

### ISSUE THREAD

**Issue by christiaanstijnen** [level-level/Clarkson-Core#140] opened 2019-02-12 15:17 UTC
in clarkson-core-templates.php > render_twig().

a new instance of Twig_Loader_Filesystem gets initiated with 2 paths. The path of the parent-theme/templates and child-theme/templates. If the parent theme has no template folder twig breaks because this directory does nog exists.

Perhaps a check if the directory exists would be a solution in get_templates_dirs().

**Comment by Mike-Hermans** [comment] 2019-02-12 15:44
Same thing happens when the child theme does not have the /templates directory and no filter is set.

**Comment by jmslbam** [comment] 2019-03-18 21:21
@Mike-Hermans Is a duplicate of https://github.com/level-level/Clarkson-Core/issues/141

Maybe update that ticket's title and close this on as the other one is already in a Milestone.

**Closed** 2019-06-18 13:15 UTC
